apiVersion: v1
kind: Pod
metadata:
  name: conversao-temperatura
  labels:
    name: conversao-temperatura
spec:
  containers:
  - name: conversao-temperatura
    image: xenxem/conversao-temperatura:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

  
  
  

